version: '3.7'
services:

  rabbit:
    image: jtn7/rabbit
    container_name: rabbit
    ports:
      - "15672:15672"
    networks:
      - frontend

  front:
    image: jtn7/php-apache
    container_name: front
    ports:
      - "8090:80"
    depends_on:
      - rabbit
    volumes:
      - ./front:/var/www/html/front/
      - ./logs/front/:/var/log/dnd/
    networks:
      - frontend

  sqldb-master:
    image: jtn7/db:master
    container_name: sqldb-master
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - backend

  sqldb-slave:
    image: jtn7/db:slave
    container_name: sqldb-slave
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - backend

  mongodb-master:
    image: mongo:4
    container_name: mongodb
    command: mongod --replSet rs0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
    - backend

  mongodb-slave:
    image: mongo:4
    container_name: mongodb
    command: mongod --replSet rs1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
    - backend

  back:
    image: jtn7/php-backend
    container_name: back
    working_dir: /step2/back
    command: ./start.sh
    volumes:
      - ./back:/step2/back
      - ./logs/back/:/var/log/dnd/
    restart: always
    depends_on:
      - sqldb-master
      - mongodb
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
