version: '3.7'
services:

  rabbit:
    image: jtn7/rabbit
    container_name: rabbitNode
    ports:
      - "15672:15672"
    networks:
      - frontend

  rabbit2:
    image: jtn7/rabbit
    container_name: rabbitNode2
    ports:
      - "15672:15672"
    networks:
      - frontend

  reverse_proxy:
    image: jtn7/reverse_proxy
    container_name: reverse_proxy
    volumes:
      - ./logs/nginx/:/var/log/nginx/
    ports:
      - "80:80"
    networks:
      - frontend

  front:
    image: jtn7/php-apache
    container_name: frontNode
    depends_on:
      - rabbit
    volumes:
      - ./front:/var/www/html/front/
      - ./logs/front/:/var/log/dnd/
    networks:
      - frontend

  front2:
    image: jtn7/php-apache
    container_name: frontNode2
    depends_on:
      - rabbit
    volumes:
      - ./front2:/var/www/html/front/
      - ./logs/front2/:/var/log/dnd/
    networks:
      - frontend

  sqldb-master:
    image: jtn7/db:master
    container_name: sqldb-master
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    networks:
      - backend

  # sqldb-slave:
  #   image: jtn7/db:slave
  #   container_name: sqldb-slave
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=pass
  #   networks:
  #     - backend

  mongodb:
    image: mongo:4
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
    - backend

  back:
    image: jtn7/php-backend
    container_name: back
    working_dir: /step2/back
    command: ./start.sh
    volumes:
      - ./back:/step2/back
      - ./logs/back/:/var/log/dnd/
    restart: always
    depends_on:
      - sqldb-master
      - mongodb
    networks:
      - frontend
      - backend

  back2:
    image: jtn7/php-backend
    container_name: back
    working_dir: /step2/back
    command: ./start.sh
    volumes:
      - ./back:/step2/back
      - ./logs/back/:/var/log/dnd/
    restart: always
    depends_on:
      - sqldb-master
      - mongodb
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
